### ISSUE TITLE
polyfill io security vulnerability

### ISSUE THREAD

**Issue by pratheeshrussell** [datagouv/cadastre.data.gouv.fr#145]
A reference to polyfill io can be seen in the file [layouts/main.js](https://github.com/datagouv/cadastre.data.gouv.fr/blob/df5261ac73f220281bcb3f93fac305edc645a549/layouts/main.js#L47). This was recently a part of a supply chain attack.   
    
It is better to replace it, a safe replacement option would be to use a polyfill from [cloudflare](https://blog.cloudflare.com/polyfill-io-now-available-on-cdnjs-reduce-your-supply-chain-risk) or from [fastly](https://community.fastly.com/t/new-options-for-polyfill-io-users/2540)     
    
You can read more about the attack in this [blog](https://sansec.io/research/polyfill-supply-chain-attack)

**Comment by ThomasG77** [comment]
The call was for supporting function es6string (template literal),Promise and fetch.
The first is supported since 2017 natively in all browsers and 2015 for the two other two. Removed via #148
